name: ExtraScenesV2
version: '${project.version}'
main: com.extracraft.extrascenesv2.ExtraScenesV2Plugin
api-version: '1.21'
author: ExtraCraft
website: https://extracraft.com
folia-supported: true
commands:
  extrascenes:
    description: Sistema de cinematics
    usage: /extrascenes <create|delete|addpoint|list|show|play|stop|reload>
    permission: extrascenes.use
permissions:
  extrascenes.use:
    description: Allows using ExtraScenes cinematic commands
    default: op
