name: ExtraScenesV2
version: '${project.version}'
main: com.extracraft.extrascenesv2.ExtraScenesV2Plugin
api-version: '1.21'
author: ExtraCraft
website: https://extracraft.com
folia-supported: true
depend: [PlaceholderAPI]
commands:
  extrascenes:
    description: Scene system
    usage: /extrascenes <create|edit|play|stop|record|actor|key|tickcmd|placeholders|delete|list|show|reload>
    aliases: [scenes]
    permission: extrascenes.use
permissions:
  extrascenes.use:
    description: Allows using ExtraScenes cinematic commands
    default: op
