name: ExtraScenesV2
version: 1.0.0
main: com.extrascenesv2.ExtraScenesPlugin
api-version: '1.20'
authors:
  - Codex
commands:
  scene:
    description: Comando principal del plugin ExtraScenesV2.
    usage: /scene
    aliases:
      - scenes
